federation_version: =2.5.3
subgraphs:
  locations:
    routing_url: https://flyby-locations-sub.herokuapp.com/
    schema:
      file: ./schemas/locations.graphql
      #subgraph_url: https://flyby-locations-sub.herokuapp.com/
  reviews:
    routing_url: https://flyby-reviews-sub.herokuapp.com/
    schema:
      file: ./schemas/reviews.graphql
      #subgraph_url: https://flyby-reviews-sub.herokuapp.com/
